// Turns data/listings.json into:
//   supabase/seed.sql      – INSERT statements for the practice listings
//   public/images/<id>.svg – a placeholder image per listing (no external image hosts)
//
// Run with: npm run generate:seed

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { loadListings, loadListingRows, projectRoot as root } from "./lib/listing-rows.mjs";

const listings = loadListings();
const rows = new Map(loadListingRows().map((r) => [r.id, r]));

const palette = [
  ["#1f2937", "#4b5563"],
  ["#7c2d12", "#c2410c"],
  ["#14532d", "#15803d"],
  ["#1e3a8a", "#2563eb"],
  ["#581c87", "#7e22ce"],
  ["#831843", "#be185d"],
  ["#78350f", "#b45309"],
  ["#134e4a", "#0f766e"],
];

const hash = (s) => [...s].reduce((h, c) => (h * 31 + c.charCodeAt(0)) >>> 0, 7);
const esc = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const sql = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);

function svgFor(l) {
  const [a, b] = palette[hash(l.brand) % palette.length];
  const initials = l.brand
    .split(/\s+/)
    .map((w) => w[0])
    .join("")
    .slice(0, 3)
    .toUpperCase();
  const title = l.title.length > 30 ? l.title.slice(0, 29) + "…" : l.title;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="480" height="480" viewBox="0 0 480 480" role="img" aria-label="${esc(l.brand)} ${esc(l.title)}">
  <defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs>
  <rect width="480" height="480" fill="url(#g)"/>
  <text x="240" y="230" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="120" font-weight="700" fill="rgba(255,255,255,0.92)">${esc(initials)}</text>
  <text x="240" y="300" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="26" fill="rgba(255,255,255,0.85)">${esc(l.brand)}</text>
  <text x="240" y="420" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="20" fill="rgba(255,255,255,0.7)">${esc(title)}</text>
</svg>
`;
}

mkdirSync(join(root, "public/images"), { recursive: true });
mkdirSync(join(root, "supabase"), { recursive: true });

const values = listings.map((l) => {
  const r = rows.get(l.id);
  writeFileSync(join(root, "public/images", `${l.id}.svg`), svgFor(l));
  return `  (${[
    sql(r.id),
    sql(r.title),
    sql(r.brand),
    r.price,
    sql(r.size),
    sql(r.image_url),
    sql(r.marketplace),
    sql(r.listing_url),
    sql(r.description),
  ].join(", ")})`;
});

const seed = `-- Generated by scripts/generate-seed.mjs from data/listings.json. Do not edit by hand.
-- Practice data only: fictional listings, no real sellers or buyers.

insert into public.listings (id, title, brand, price, size, image_url, marketplace, listing_url, description) values
${values.join(",\n")}
on conflict (id) do update set
  title = excluded.title,
  brand = excluded.brand,
  price = excluded.price,
  size = excluded.size,
  image_url = excluded.image_url,
  marketplace = excluded.marketplace,
  listing_url = excluded.listing_url,
  description = excluded.description;
`;

writeFileSync(join(root, "supabase/seed.sql"), seed);
console.log(`Wrote supabase/seed.sql and ${listings.length} images to public/images/`);
